:hammer: Tidy up the setup-* scripts

diff --git a/libexec/handles-setup-nginx-conf b/libexec/handles-setup-nginx-conf
--- a/libexec/handles-setup-nginx-conf
+++ b/libexec/handles-setup-nginx-conf
@@ -4,7 +4,8 @@
 # Hidden: true
 
 set -e
-cd "$(git rev-parse --show-toplevel)"
+
+cd "$(git rev-parse --show-toplevel 2>/dev/null)"
 
 INPUT_FILE="${2-"nginx.conf.erb"}"
 OUTPUT_FILE="${PWD}/${INPUT_FILE//.erb}"
@@ -32,6 +33,11 @@ if [ "$(uname -s)" = "Darwin" ]; then
     "brew 'launchdns', restart_service: true"
   )
   PREFIX="$(brew --prefix)"
+
+  if ! command -v brew >/dev/null 2>&1; then
+    echo "!!! Error: brew is not installed" >&2
+    exit 1
+  fi
 
   OLDIFS="$IFS" IFS=$'\n'
   echo "${BREWFILE[*]}" | brew bundle check --file=- >/dev/null || {
