:sparkles: Bump the version if needed when releasing

diff --git a/libexec/handles-release b/libexec/handles-release
--- a/libexec/handles-release
+++ b/libexec/handles-release
@@ -58,9 +58,30 @@ elif [ -n "$CURRENT_VERSION" ] && [ "$(git rev-list --count "$CURRENT_VERSION"..
   exit 1
 fi
 
-echo "==> Tagging version…"
+if [ -f "package.json" ]; then
+  echo "==> Bumping version…"
+
+  if ! npm version --no-git-tag-version "${VERSION#v}" &>/dev/null; then
+    echo "!!! Error: failed to bump version" >&2
+    exit 1
+  fi
+
+  test -f "npm-shrinkwrap.json" && git add --update npm-shrinkwrap.json
+  test -f "package-lock.json" && git add --update package-lock.json
+  git add --update package.json
+fi
+
+if ! git diff-index --cached --quiet HEAD --; then
+  echo "==> Preparing release…"
+  if ! git commit -m ":bookmark: Release ${VERSION}" &>/dev/null; then
+    echo "!!! Error: failed to prepare release" >&2
+    exit 1
+  fi
+fi
+
+echo "==> Tagging release…"
 if ! git tag -s "$VERSION" -m ":bookmark: Tag ${VERSION}" &>/dev/null; then
-  echo "!!! Error: failed to tag version" >&2
+  echo "!!! Error: failed to tag release" >&2
   exit 1
 fi
 
