setup: symlink in an nginx server configuration file

diff --git a/libexec/handles-setup b/libexec/handles-setup
--- a/libexec/handles-setup
+++ b/libexec/handles-setup
@@ -8,8 +8,17 @@ cd "$(git rev-parse --show-toplevel)"
 handles-bootstrap
 
 if [ -f ".env.example" ]; then
-  echo "==> Creating .env file…"
+  echo "==> Copying environment file…"
   cp .env.example .env
+fi
+
+if [ -f "nginx.conf" ] && [ "$(uname -s)" = "Darwin" ]; then
+  echo "==> Symlinking nginx server configuration file…"
+  ln -sf nginx.conf "$(brew --prefix)/etc/nginx/servers/$(basename $PWD).conf"
+  if ! brew services restart nginx &>/dev/null; then
+    echo "!!! Error: failed to (re)start nginx!" >&2
+    exit 1
+  fi
 fi
 
 echo "==> Your project is now ready to go!"
