:art: Improve the handling of an initial release

diff --git a/libexec/handles-release b/libexec/handles-release
--- a/libexec/handles-release
+++ b/libexec/handles-release
@@ -6,9 +6,7 @@ set -e
 
 cd "$(git rev-parse --show-toplevel 2>/dev/null)"
 
-CURRENT_VERSION="$(git describe --tags --abbrev=0 --match='v[0-9]*' 2>/dev/null || true)"
 VERSION="$1"
-VERSION_REGEX="^v(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))?)?$"
 
 if [ -z "$VERSION" ]; then
   handles help release >&2
@@ -25,31 +23,35 @@ elif [ ! -z "$(git status --porcelain 2>/dev/null)" ]; then
 elif ! git fetch --quiet --tags origin; then
   echo "!!! Error: running 'git fetch' failed" >&2
   exit 1
-elif [ -n "$CURRENT_VERSION" ] && [ "$(git rev-list --count "$CURRENT_VERSION"..HEAD)" == "0" ]; then
-  echo "!!! Error: there have been no commits since the last version" >&2
-  exit 1
 elif [ "$(git rev-list --count HEAD..origin/master)" != "0" ]; then
   echo "!!! Error: there have been upstream changes on master" >&2
   exit 1
 fi
 
-if [ -n "$CURRENT_VERSION" ] && [[ "$CURRENT_VERSION" =~ $VERSION_REGEX ]]; then
+CURRENT_VERSION="$(git describe --tags --abbrev=0 --match='v[0-9]*' 2>/dev/null || true)"
+VERSION_REGEX="^v(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))?)?$"
+
+if [[ "$CURRENT_VERSION" =~ $VERSION_REGEX ]]; then
   MAJOR="${BASH_REMATCH[1]}"
   MINOR="${BASH_REMATCH[3]}"
   PATCH="${BASH_REMATCH[5]}"
-
-  case $VERSION in
-    +major|+M) VERSION="v$((${MAJOR:-0} + 1))${MINOR:+.0}${PATCH:+.0}" ;;
-    +minor|+m) VERSION="v${MAJOR:-0}.$((${MINOR:-0} + 1))${PATCH:+.0}" ;;
-    +patch|+p) VERSION="v${MAJOR:-0}.${MINOR:-0}.$((${PATCH:-0} + 1))" ;;
-  esac
+elif [ -z "$CURRENT_VERSION" ]; then
+  MAJOR="0"
+  MINOR="0"
+  PATCH="0"
 fi
 
-if [[ "$VERSION" =~ ^\+(major|minor|patch|M|m|p)$ ]]; then
-  echo "!!! Error: you cannot bump release the first version";
-  exit 1;
-elif [[ ! "$VERSION" =~ $VERSION_REGEX ]]; then
+case $VERSION in
+  +major|+M) VERSION="v$((${MAJOR:-0} + 1))${MINOR:+.0}${PATCH:+.0}" ;;
+  +minor|+m) VERSION="v${MAJOR:-0}.$((${MINOR:-0} + 1))${PATCH:+.0}" ;;
+  +patch|+p) VERSION="v${MAJOR:-0}.${MINOR:-0}.$((${PATCH:-0} + 1))" ;;
+esac
+
+if [[ ! "$VERSION" =~ $VERSION_REGEX ]]; then
   echo "!!! Error: invalid version: ${VERSION}" >&2
+  exit 1
+elif [ -n "$CURRENT_VERSION" ] && [ "$(git rev-list --count "$CURRENT_VERSION"..HEAD)" == "0" ]; then
+  echo "!!! Error: there are no commits to release" >&2
   exit 1
 elif git describe --exact-match "$VERSION" &>/dev/null; then
   echo "!!! Error: ${VERSION} tag already exists" >&2
@@ -59,7 +61,7 @@ fi
 echo "==> Generating release notes…"
 printf "%s\n\n" "$VERSION" > .git/RELEASE_EDITMSG
 if [ -n "$CURRENT_VERSION" ]; then
-  git log  --reverse --no-merges --format='- %s' "$CURRENT_VERSION"...HEAD | grep -v ":bookmark:"
+  git log  --reverse --no-merges --format='- %s' "$CURRENT_VERSION"..HEAD | grep -v ":bookmark:"
 else
   echo ":tada: Initial release"
 fi >> .git/RELEASE_EDITMSG
